#!/bin/bash
for i in {2..17}
do
j=$(expr $i - 1)	
echo $j
st=$(echo "$j * 86400000" | bc)
st=$(expr $st + 1295740800000)
et=$(expr $st + 86400000)
	echo "day $i , starts $st and ends $et"
	/u2/yaboulnaga/Programs/hadoop-1.0.3/bin/hadoop jar target/assoc-mr-0.0.2-SNAPSHOT-job.jar org.apache.mahout.freqtermsets.FPGrowthDriver --input file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/rawtweets_csv_hour-5min/ --output file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/assoc-mr_chuncks-5min-shifted_day$i/ -j 4 -mf 3 --minSupport 2 -pct 99 -g 256 -ws 300000 -shift -st $st -et $et
        /u2/yaboulnaga/Programs/hadoop-1.0.3/bin/hadoop jar target/assoc-mr-0.0.2-SNAPSHOT-job.jar org.apache.mahout.freqtermsets.FPGrowthDriver --input file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/rawtweets_csv_hour-5min/ --output file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/assoc-mr_chuncks-15min-shifted_day$i/ -j 4 -mf 3 --minSupport 2 -pct 99 -g 256 -ws 900000 -shift  -st $st -et $et
        /u2/yaboulnaga/Programs/hadoop-1.0.3/bin/hadoop jar target/assoc-mr-0.0.2-SNAPSHOT-job.jar org.apache.mahout.freqtermsets.FPGrowthDriver --input file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/rawtweets_csv_hour-5min/ --output file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/assoc-mr_chuncks-30min-shifted_day$i/ -j 4 -mf 3 --minSupport 2 -pct 99 -g 256 -ws 1800000 -shift -st $st -et $et
        /u2/yaboulnaga/Programs/hadoop-1.0.3/bin/hadoop jar target/assoc-mr-0.0.2-SNAPSHOT-job.jar org.apache.mahout.freqtermsets.FPGrowthDriver --input file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/rawtweets_csv_hour-5min/ --output file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/assoc-mr_chuncks-1hr-shifted_day$i/ -j 4 -mf 3 --minSupport 2 -pct 99 -g 256 -ws 3600000 -shift -st $st -et $et
        /u2/yaboulnaga/Programs/hadoop-1.0.3/bin/hadoop jar target/assoc-mr-0.0.2-SNAPSHOT-job.jar org.apache.mahout.freqtermsets.FPGrowthDriver --input file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/rawtweets_csv_hour-5min/ --output file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/assoc-mr_chuncks-2hr-shifted_day$i/ -j 4 -mf 3 --minSupport 2 -pct 99 -g 256 -ws 7200000 -shift -st $st -et $et
        /u2/yaboulnaga/Programs/hadoop-1.0.3/bin/hadoop jar target/assoc-mr-0.0.2-SNAPSHOT-job.jar org.apache.mahout.freqtermsets.FPGrowthDriver --input file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/rawtweets_csv_hour-5min/ --output file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/assoc-mr_chuncks-4hr-shifted_day$i/ -j 4 -mf 3 --minSupport 2 -pct 99 -g 256 -ws 14400000 -shift -st $st -et $et
        /u2/yaboulnaga/Programs/hadoop-1.0.3/bin/hadoop jar target/assoc-mr-0.0.2-SNAPSHOT-job.jar org.apache.mahout.freqtermsets.FPGrowthDriver --input file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/rawtweets_csv_hour-5min/ --output file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/assoc-mr_chuncks-8hr-shifted_day$i/ -j 4 -mf 3 --minSupport 2 -pct 99 -g 256 -ws 28800000 -shift -st $st -et $et
#        /u2/yaboulnaga/Programs/hadoop-1.0.3/bin/hadoop jar target/assoc-mr-0.0.2-SNAPSHOT-job.jar org.apache.mahout.freqtermsets.FPGrowthDriver --input file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/rawtweets_csv_hour-5min/ --output file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/assoc-mr_chuncks-16hr-shifted_day$i/ -j 4 -mf 3 --minSupport 2 -pct 99 -g 256 -ws 57600000 -shift -st $st -et $et
       /u2/yaboulnaga/Programs/hadoop-1.0.3/bin/hadoop jar target/assoc-mr-0.0.2-SNAPSHOT-job.jar org.apache.mahout.freqtermsets.FPGrowthDriver --input file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/rawtweets_csv_hour-5min/ --output file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/assoc-mr_chuncks-24hr-shifted_day$i/ -j 4 -mf 3 --minSupport 2 -pct 99 -g 256 -ws 86400000 -shift -st $st -et $et
#        /u2/yaboulnaga/Programs/hadoop-1.0.3/bin/hadoop jar target/assoc-mr-0.0.2-SNAPSHOT-job.jar org.apache.mahout.freqtermsets.FPGrowthDriver --input file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/rawtweets_csv_hour-5min/ --output file:///u2/yaboulnaga/Shared/datasets/twitter-trec2011/assoc-mr_chuncks-32hr-shifted_day$i/ -j 4 -mf 3 --minSupport 2 -pct 99 -g 256 -ws 115200000 -shift -st $st -et $et
done
